version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test